/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedPalpitesRouteImport } from './routes/_authenticated/palpites'
import { Route as AdminBotRouteImport } from './routes/admin/bot'
import { Route as ApiBotPredictionsRouteImport } from './routes/api/bot-predictions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPalpitesRoute = AuthenticatedPalpitesRouteImport.update({
  id: '/palpites',
  path: '/palpites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminBotRoute = AdminBotRouteImport.update({
  id: '/admin/bot',
  path: '/admin/bot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotPredictionsRoute = ApiBotPredictionsRouteImport.update({
  id: '/api/bot-predictions',
  path: '/api/bot-predictions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/palpites': typeof AuthenticatedPalpitesRoute
  '/admin/bot': typeof AdminBotRoute
  '/api/bot-predictions': typeof ApiBotPredictionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/palpites': typeof AuthenticatedPalpitesRoute
  '/admin/bot': typeof AdminBotRoute
  '/api/bot-predictions': typeof ApiBotPredictionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/palpites': typeof AuthenticatedPalpitesRoute
  '/admin/bot': typeof AdminBotRoute
  '/api/bot-predictions': typeof ApiBotPredictionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/palpites' | '/admin/bot' | '/api/bot-predictions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/palpites' | '/admin/bot' | '/api/bot-predictions'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/palpites'
    | '/admin/bot'
    | '/api/bot-predictions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  AdminBotRoute: typeof AdminBotRoute
  ApiBotPredictionsRoute: typeof ApiBotPredictionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/palpites': {
      id: '/_authenticated/palpites'
      path: '/palpites'
      fullPath: '/palpites'
      preLoaderRoute: typeof AuthenticatedPalpitesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/bot': {
      id: '/admin/bot'
      path: '/admin/bot'
      fullPath: '/admin/bot'
      preLoaderRoute: typeof AdminBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bot-predictions': {
      id: '/api/bot-predictions'
      path: '/api/bot-predictions'
      fullPath: '/api/bot-predictions'
      preLoaderRoute: typeof ApiBotPredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPalpitesRoute: typeof AuthenticatedPalpitesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPalpitesRoute: AuthenticatedPalpitesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  AdminBotRoute: AdminBotRoute,
  ApiBotPredictionsRoute: ApiBotPredictionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
